### ISSUE TITLE
No longer works with latest version of atom master

### ISSUE THREAD

**Issue by benogle** [efatsi/block-travel#17]
Moves to the top or bottom of the file. I wonder if some API behavior changed?

Bug likely present on current atom beta (1.9.0-beta0).

**Comment by 526avijitgupta** [comment]
Doesn't work with the latest version. There's just no movement when pressing <kbd>Alt up/down</kbd>
Though it does work when invoked from the command pallete.

**Comment by hmatsuda** [comment]
It does work on 1.9.0-beta0 on osx.

**Comment by leejarvis** [comment]
Thanks, sorry I haven't gotten back to anyone. Unfortunately I no longer use Atom and don't have the time to maintain this package. I'll update the README appropriately. If anyone would like to maintain the package or can provide an alternative I can add it to the README. Thanks

**Comment by benogle** [comment]
Feel free to add me to this repo--I can maintain.

**Comment by leejarvis** [comment]
Thanks Ben, I've added you.

**Comment by benogle** [comment]
This is due to https://github.com/atom/atom/issues/12149

**Comment by dcsan** [comment]
hey, this is a super useful package, i wondered why it stopped working. @benogle i've never touched developing an atom plugin but let me know if i could help at all!

**Comment by dcsan** [comment]
@benogle i guess you took over a month ago, i'm wondering if you had time to look into this, or if there's another package you recommend with similar functionality?

**Comment by efatsi** [comment]
@dcsan there's a fix for this problem (by @benogle) in a separate branch - https://github.com/leejarvis/block-travel/tree/bo-fix-for-invisibles. Hopefully it'll be merged in and pushed to atom soon, but if you're comfortable pulling the repo down and using the package locally functionality will be restored.

**Comment by benogle** [comment]
I do it later today, sorry for the delay.

**Comment by dcsan** [comment]
@benogle much appreciated. I haven't build an atom package yet and it would probably take longer to find time to do than to just wait... thanks!

**Comment by efatsi** [comment]
@dcsan @benogle I've merged in the patch and pushed a new version 1.0.5. Should be working now!

**Comment by dcsan** [comment]
awesome, happy camping again 🚀

**Comment by benogle** [comment]
ok, word. thanks
