### ISSUE TITLE
Cursor position

### ISSUE THREAD

**Issue by Michal-Mikolas** [efatsi/block-travel#18]
Now, if traveling around blocks, cursor always stops on empty line.  

It would be great if cursor stops at beginning / ending of the block. 
Like this: https://atom.io/packages/space-block-jumper

Thank you!

**Comment by efatsi** [comment]
@Michal-Mikolas sounds like a decent idea to have that be available as a configuration option for the package. Are you up to the task of implementing that and submitting a PR?
