### ISSUE TITLE
clashes with multiline select?

### ISSUE THREAD

**Issue by dcsan** [efatsi/block-travel#19]
I love this extension, but for some reason it doesn't work on my home machine.

(on a mac) instead the option-up is doing a multiline select.

however `shift-option-up` will select a whole block.

as a fallback I added this to keymap.cson to use the ctrl rather than alt/option but would prefer consistency. any ideas where else to look?

```
'.editor':
  'ctrl-up': 'block-travel:move-up'
  'ctrl-down': 'block-travel:move-down'
  'ctrl-shift-up': 'block-travel:select-up'
  'ctrl-shift-down': 'block-travel:select-down'
```

**Comment by benogle** [comment]
Maybe another thing is clobbering it. Can you try the keybinding resolver? `cmd-.` will open it, then push the binding, and let me know what it says.

**Comment by dcsan** [comment]
thanks! it was the multi-cursor package it seems.
https://atom.io/packages/multi-cursor

I thought multi-cursor was a built in atom thing, didn't recall installing that...
