### ISSUE TITLE
Not working at all.

### ISSUE THREAD

**Issue by alexanderisora** [efatsi/block-travel#21]
Hello!
I'm using Atom 1.17.2 x64 on OSX Sierra. The plugin is not working at all. Any thoughts?

**Comment by doggan** [comment]
I was having issues as well. After searching, it seems similar functionality was added to atom core a while ago, so you can get the same behavior without an add-on.

Just add this to your `keymap.cson` file:
```
'.editor':
  'alt-up': 'editor:move-to-beginning-of-previous-paragraph'
  'alt-down': 'editor:move-to-beginning-of-next-paragraph'
  'alt-shift-up': 'editor:select-to-beginning-of-previous-paragraph'
  'alt-shift-down': 'editor:select-to-beginning-of-next-paragraph'
```

**Comment by efatsi** [comment]
@doggan nice find! good to see this functionality has been developed in atom core, i'll update the readme now that this project is defunct.

**Comment by doggan** [comment]
@efatsi Thanks for your work (and previous contributors). This was an essential package for me while it lasted.
