### ISSUE TITLE
Package doesn't work

### ISSUE THREAD

**Issue by Ronnyrr** [efatsi/block-travel#23]
Hi there,

I was really looking for a package like this one.
Unfortunately it doesn't work like expected. In fact, it doens't do anything at all. 
I've working mostly in .jsx files, but also in .js or .scss files the package doesn't do it's tricks. Any head up or suggestions for what I do wrong?

**Comment by efatsi** [comment]
Hey @Ronnyrr, any more information you could provide? Questions I'd be curious about: Are you certain that the package's commands are being triggered? Opening the command palette and triggering the actions from there should guarantee that. Can you open up the dev console (cmd-opt-i) and see if there are any console errors?

**Comment by Ronnyrr** [comment]
Thanks for the heads up.
Emmet for overriding the block travel keybindings. Added custom (more specific) keybindings and now it works! 

![screen shot 2017-09-22 at 15 52 21](https://user-images.githubusercontent.com/4519142/30747603-1142d63a-9fae-11e7-89ef-0a9acb02f613.png)
