### ISSUE TITLE
Traveling two blocks at a time

### ISSUE THREAD

**Issue by jacquesn** [efatsi/block-travel#24]
Just today the move-up and move-down bindings started to be overridden by editor:select-larger-syntax-node and editor:select-smaller-syntax-node, so I bound move-up and move-down in the keymap. The bindings worked again, but now it travels two blocks at a time, both for move-up/down and select-up/down.

**Comment by efatsi** [comment]
@jacquesn I noticed that as well, this worked for me in my keybindings:

```cson
# re-aliasing defaults to not interfere with package keybindings
'atom-text-editor:not([mini])':
  'alt-down': 'block-travel:move-down'
  'alt-up': 'block-travel:move-up'
```

I imagine the command is being triggered for you twice somehow. Perhaps an `!unset` keybinding addition will break the execution flow?

**Comment by jacquesn** [comment]
Well, Atom bugged out and froze on me while I was trying to debug it. After a force quit and reopen, block-travel worked correctly again. So I don't know what the problem was, but I've gone ahead and changed my keymap to match yours, and it still works that way too. Hopefully that will take care of any repeats of the buggy behavior. Thanks!

**Comment by efatsi** [comment]
Yeah, keybindings have given me the most frustration in working with Atom. Glad you got things figured out though!
